### ISSUE TITLE
CREATE Subscriptions don't fire at all

### ISSUE THREAD

**Issue by stigi** [prismagraphql/prisma#2824]
**Describe the bug**

A very simple subscription in a brand new project initialized with `prisma init` does not fire.

**To Reproduce**
1. Create a new project `prisma init subscriptions`
    1. Demo server (Also tried `Create new database` with local Postgres)
    2. Hosted on eu-west-1 (Also tried us-west-2)
2. `cd subscriptions; prisma deploy`
3. Open playground
4. Start the subscription
5. Perform the mutation

Subscription:

```
subscription S {
  user {
    mutation
    node {
      id
      name
    }
  }
}
```

Mutation:

```
mutation M {
  createUser(data: {name: "Dale Cooper"}) {
    id
    name
  }
}
```

**Expected behavior**

The newly created user appears with same id and name in the subscription response.

**Versions (please complete the following information):**
 - OS: macOS 10.13.6 (17G65) on Safari Version 12.0 (13606.1.24.40.1)
 - `prisma` CLI: prisma/1.12.1 (darwin-x64) node-v9.11.2
 - Prisma Server: 1.10.2 (the one from https://app.prisma.io/[my-id]/servers, right?)

**Additional context**

Reported in Slack: https://prisma.slack.com/archives/CA491RJH0/p1532788526000012

I took a look at the network inspector. The websocket is opened, and I get a `{"type":"connection_ack"}` response, as well as many `{"type":"ka"}` (btw: they don’t stop when I stop the subscription).  Not sure where to dig deeper right now.

**Comment by stigi** [comment]
Looks the same as #2819

**Comment by stigi** [comment]
Tried an update mutation and the subscription did fire:

```
mutation M {
  updateUser(
    where: { id: "cjk5w0fgs250j0c55war2qykk" }
    data: { name: "Agent Cooper" }
  ) {
    id
    name
  }
}
```

**Comment by divyenduz** [comment]
I am able to reproduce this issue. I can confirm that the subscription 

1. Does not fire for `CREATED`
1. Works for `UPDATED`
1. Returns null node for `DELETED`
```
{
  "data": {
    "user": {
      "node": null
    }
  }
}
```

**Comment by timkendall** [comment]
Confirmed with `1.12` as well (running on AWS Fargate + RDS w/MySQL if that helps)

**Comment by frankdugan3** [comment]
I'm having the same issue (null for `DELETED`, no firing on `CREATED`, `UPDATED` works).

I'm using `1.12.2`, MySQL.

**Comment by Enricopv** [comment]
I'm having the same `CuidGCValue(...)` issue as @frankdugan3, but only when subscribed to `DELETED` events. `UPDATED` returns id in `previousValues` perfectly fine (for me).

**Comment by timkendall** [comment]
Looks like this has been addressed in `1.12.3` https://github.com/prismagraphql/prisma/releases/tag/1.12.3 👍

**Comment by frankdugan3** [comment]
@timkendall Yes, but that `CuidGCValue(...)` issue is still happening on `DELETED` `previousValues` `id`, even in `1.13.1`. Maybe I should open a separate issue for that?

**Comment by divyenduz** [comment]
@frankdugan3 : Please open a separate issue for that and tag me on it. Closing this one as the originally reported issue is resolved. Thanks for the feedback everyone 🙌
